**TASK** **4**

*Part* 1: *Review* *prediction*

In [2]:
#Import libraries
import numpy as numpy
import pandas as pd
import nltk
from nltk.corpus import stopwords
import string

In [3]:
#Loading file
from google.colab import files
uploaded = files.upload()

Saving processed_reviews_split_surnamesK_minimal4.csv to processed_reviews_split_surnamesK_minimal4.csv


In [4]:
data = pd.read_csv('processed_reviews_split_surnamesK_minimal4.csv')

data.head(5)

review_id                                               text  \
0  product_review_000000  Though this game is still very good, it's can'...   
1  product_review_000001  best game everust like being on the field.  th...   
2  product_review_000002  Battlefield One is a great game, it offers a l...   
3  product_review_000003  No doubt there will be improvements in portabl...   
4  product_review_000004  This is my first Animal Crossing game so go ea...   

  verified  review_score product_category  
0    False           3.0      video_games  
1     True           5.0      video_games  
2     True          -1.0      video_games  
3    False           5.0              NaN  
4    False           4.0      video_games

In [5]:
data.shape

(32918, 5)

In [6]:
data.describe()

review_score
count  32918.000000
mean       4.089222
std        1.433766
min       -1.000000
25%        4.000000
50%        5.000000
75%        5.000000
max        5.000000

In [7]:
#Checking for duplicates and removing them

data.drop_duplicates(inplace=True)

In [8]:
data.shape

(32918, 5)

In [9]:
## Checking for missing data and dropping them

data.isnull()

review_id   text  verified  review_score  product_category
0          False  False     False         False             False
1          False  False     False         False             False
2          False  False     False         False             False
3          False  False     False         False              True
4          False  False     False         False             False
...          ...    ...       ...           ...               ...
32913      False  False     False         False             False
32914      False  False     False         False             False
32915      False  False     False         False             False
32916      False  False     False         False             False
32917      False  False     False         False             False

[32918 rows x 5 columns]

In [10]:
data.isnull().sum()

review_id             0
text                 11
verified            120
review_score          0
product_category    906
dtype: int64

In [11]:
data = data.dropna()

In [12]:
data.shape

(31888, 5)

In [14]:
data.isnull().sum()

review_id           0
text                0
verified            0
review_score        0
product_category    0
dtype: int64

In [15]:
## Downloading stopword package
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [17]:
def text_process(text):
  # Punctutaion removal
  no_punc = [char for char in text if char not in string.punctuation]
  no_punc = ''.join(no_punc)

  # Stopwords removal
  clean_words = [word for word in no_punc.split() if word.lower() not in stopwords.words('english')]
  return clean_words 


In [18]:
data['text'].head().apply(text_process)

0    [Though, game, still, good, cant, compete, cur...
1    [best, game, everust, like, field, pitchin, hi...
2    [Battlefield, One, great, game, offers, lot, f...
4    [first, Animal, Crossing, game, go, easy, game...
5    [cute, mic, us, working, musicians, need, cute...
Name: text, dtype: object

In [20]:
## Converting message corpus into tokens
from sklearn.feature_extraction.text import CountVectorizer
text_bow = CountVectorizer(analyzer=text_process).fit_transform(data['text']) 

In [30]:
## Splitting data
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(text_bow, data['review_score'], test_size=0.33, random_state=0)

In [31]:
text_bow.shape

(31888, 83056)

In [32]:
## Developing classification models using Multinomial Naive Bayes
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB().fit(X_train, y_train)

In [33]:
# Printing the predictions
print(clf.predict(X_train))

# Printing actual values
print(y_train.values)

[5. 5. 5. ... 5. 5. 5.]
[ 1.  5.  5. ... -1.  4.  5.]


In [34]:
# Evaluating model on training dataset
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
pred = clf.predict(X_test)
print(classification_report(y_test, pred))
print()
print('Confusion matrix: \n', confusion_matrix(y_test, pred))

              precision    recall  f1-score   support

        -1.0       0.00      0.00      0.00       298
         1.0       0.58      0.12      0.20       612
         2.0       0.41      0.01      0.03       495
         3.0       0.26      0.05      0.09       991
         4.0       0.30      0.23      0.26      1911
         5.0       0.66      0.92      0.77      6217

    accuracy                           0.60     10524
   macro avg       0.37      0.22      0.22     10524
weighted avg       0.52      0.60      0.52     10524


Confusion matrix: 
 [[   0    7    0   10   36  245]
 [   1   73    7   51  101  379]
 [   0   10    7   45  144  289]
 [   2    5    0   52  308  624]
 [   4    4    1   16  431 1455]
 [  21   26    2   24  403 5741]]


In [35]:
print('Accuracy: ', accuracy_score(y_test, pred))

Accuracy:  0.5990117825921702


In [36]:
## Developing classification models using Decision tree Classifier
from sklearn.tree import DecisionTreeClassifier
tree = DecisionTreeClassifier().fit(X_train, y_train)

In [37]:
print(tree.predict(X_train))


[ 1.  5.  5. ... -1.  4.  5.]


In [38]:
pred_dt = tree.predict(X_test)
print(classification_report(y_test, pred_dt))
print()
print('Confusion matrix: \n', confusion_matrix(y_test, pred_dt))

              precision    recall  f1-score   support

        -1.0       0.01      0.01      0.01       298
         1.0       0.29      0.25      0.27       612
         2.0       0.13      0.11      0.12       495
         3.0       0.22      0.20      0.21       991
         4.0       0.27      0.29      0.28      1911
         5.0       0.69      0.69      0.69      6217

    accuracy                           0.50     10524
   macro avg       0.27      0.26      0.27     10524
weighted avg       0.50      0.50      0.50     10524


Confusion matrix: 
 [[   3   17   14   34   55  175]
 [  23  156   53   63  100  217]
 [  20   54   56   71   98  196]
 [  37   56   64  202  244  388]
 [  84   66   82  182  561  936]
 [ 221  185  156  365  988 4302]]


In [39]:
print('Accuracy: ', accuracy_score(y_test, pred_dt))

Accuracy:  0.5017103762827823


*Part *2*: *Product_category*



```
# This is formatted as code
```



In [52]:
data

review_id  \
0      product_review_000000   
1      product_review_000001   
2      product_review_000002   
4      product_review_000004   
5      product_review_000005   
...                      ...   
32913  product_review_032913   
32914  product_review_032914   
32915  product_review_032915   
32916  product_review_032916   
32917  product_review_032917   

                                                    text verified  \
0      Though this game is still very good, it's can'...    False   
1      best game everust like being on the field.  th...     True   
2      Battlefield One is a great game, it offers a l...     True   
4      This is my first Animal Crossing game so go ea...    False   
5      This is a very cute mic. But most of us workin...     True   
...                                                  ...      ...   
32913  It will make a child happy. It is good for the...     True   
32914                                          Sweat!!.      True   
32915  No brainer - tons of new stuff and days of add...     True   
32916  I got this game because I like sid meier's oth...     True   
32917  Easy to use, GREAT sound - now my favorite ped...     True   

       review_score     product_category  
0               3.0          video_games  
1               5.0          video_games  
2              -1.0          video_games  
4               4.0          video_games  
5               3.0  musical_instruments  
...             ...                  ...  
32913           4.0  musical_instruments  
32914           4.0          video_games  
32915           5.0          video_games  
32916           4.0          video_games  
32917           5.0  musical_instruments  

[31888 rows x 5 columns]

In [40]:
## Generating dummy variables for "produc_category"
data_new = pd.get_dummies(data, columns=['product_category'])
data_new.head()

review_id                                               text  \
0  product_review_000000  Though this game is still very good, it's can'...   
1  product_review_000001  best game everust like being on the field.  th...   
2  product_review_000002  Battlefield One is a great game, it offers a l...   
4  product_review_000004  This is my first Animal Crossing game so go ea...   
5  product_review_000005  This is a very cute mic. But most of us workin...   

  verified  review_score  product_category_musical_instruments  \
0    False           3.0                                     0   
1     True           5.0                                     0   
2     True          -1.0                                     0   
4    False           4.0                                     0   
5     True           3.0                                     1   

   product_category_video_games  
0                             1  
1                             1  
2                             1  
4                             1  
5                             0

In [41]:
data_new= data_new.drop(['product_category_video_games'], axis = 1)

In [42]:
data_new

review_id  \
0      product_review_000000   
1      product_review_000001   
2      product_review_000002   
4      product_review_000004   
5      product_review_000005   
...                      ...   
32913  product_review_032913   
32914  product_review_032914   
32915  product_review_032915   
32916  product_review_032916   
32917  product_review_032917   

                                                    text verified  \
0      Though this game is still very good, it's can'...    False   
1      best game everust like being on the field.  th...     True   
2      Battlefield One is a great game, it offers a l...     True   
4      This is my first Animal Crossing game so go ea...    False   
5      This is a very cute mic. But most of us workin...     True   
...                                                  ...      ...   
32913  It will make a child happy. It is good for the...     True   
32914                                          Sweat!!.      True   
32915  No brainer - tons of new stuff and days of add...     True   
32916  I got this game because I like sid meier's oth...     True   
32917  Easy to use, GREAT sound - now my favorite ped...     True   

       review_score  product_category_musical_instruments  
0               3.0                                     0  
1               5.0                                     0  
2              -1.0                                     0  
4               4.0                                     0  
5               3.0                                     1  
...             ...                                   ...  
32913           4.0                                     1  
32914           4.0                                     0  
32915           5.0                                     0  
32916           4.0                                     0  
32917           5.0                                     1  

[31888 rows x 5 columns]

In [44]:
X_train2,X_test2,y_train2,y_test2 = train_test_split(text_bow, data_new['product_category_musical_instruments'], test_size=0.33, random_state=0)

In [45]:
clf2 = MultinomialNB().fit(X_train2, y_train2)

In [48]:
print(clf.predict(X_train2))




[5. 5. 5. ... 5. 5. 5.]


In [49]:
print(y_train2.values)

[0 0 0 ... 0 1 0]


In [50]:
## Predicting video category with Multinomial Naive Bayes
pred2 = clf2.predict(X_test)
print(classification_report(y_test2, pred2))
print()
print('Confusion matrix: \n', confusion_matrix(y_test, pred2))

              precision    recall  f1-score   support

           0       0.97      0.92      0.94      7131
           1       0.85      0.94      0.89      3393

    accuracy                           0.93     10524
   macro avg       0.91      0.93      0.92     10524
weighted avg       0.93      0.93      0.93     10524


Confusion matrix: 
 [[   0  202   96    0    0    0    0]
 [   0    0    0    0    0    0    0]
 [   0  484  128    0    0    0    0]
 [   0  361  134    0    0    0    0]
 [   0  716  275    0    0    0    0]
 [   0 1295  616    0    0    0    0]
 [   0 3698 2519    0    0    0    0]]


In [51]:
print('Accuracy: ', accuracy_score(y_test2, pred2))

Accuracy:  0.9269289243633599


In [53]:
## Using Decision tree classifier
tree2 = DecisionTreeClassifier().fit(X_train2, y_train2)

In [54]:
pred_dt2 = tree.predict(X_test2)
print(classification_report(y_test2, pred_dt2))
print()
print('Confusion matrix: \n', confusion_matrix(y_test2, pred_dt2))

              precision    recall  f1-score   support

        -1.0       0.00      0.00      0.00         0
         0.0       0.00      0.00      0.00      7131
         1.0       0.24      0.04      0.07      3393
         2.0       0.00      0.00      0.00         0
         3.0       0.00      0.00      0.00         0
         4.0       0.00      0.00      0.00         0
         5.0       0.00      0.00      0.00         0

    accuracy                           0.01     10524
   macro avg       0.03      0.01      0.01     10524
weighted avg       0.08      0.01      0.02     10524


Confusion matrix: 
 [[   0    0    0    0    0    0    0]
 [ 266    0  404  315  649 1473 4024]
 [ 122    0  130  110  268  573 2190]
 [   0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0]]


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1

In [56]:
pred_dt2

array([5., 5., 4., ..., 5., 4., 3.])

In [55]:
print('Accuracy: ', accuracy_score(y_test2, pred_dt2))

Accuracy:  0.012352717597871531
